
EXCEPTION (PART 1)


__ July 2, 2015July 20, 2015 __ An

Java menggunakan _exception_ untuk mengendalikan _error_. Apabila
_error_ berlaku, _exception_ ini dilancarkan untuk menghentikan proses
yang mempunyai _error_.

Cara mudah untuk menghasilkan _error_ adalah dengan membahagikan satu
nombor dengan kosong:

package essential; public class BahagiKosong { public static void
main(String[] args) { int a = 1 / 0; } }

+--------------------------------------+--------------------------------------+
| 1                                    | package essential;                   |
|                                      |                                      |
| 2                                    |                                      |
|                                      |                                      |
| 3                                    | public class BahagiKosong {          |
|                                      |                                      |
| 4                                    |     public static void main(String[] |
|                                      | args) {                              |
| 5                                    |                                      |
|                                      |         int a = 1 / 0;               |
| 6                                    |                                      |
|                                      |     }                                |
| 7                                    |                                      |
|                                      | }                                    |
+--------------------------------------+--------------------------------------+

Apabila kita _run_ code tersebut, program akan keluarkan teks
menjelaskan tentang _error_ tersebut, iaitu _‘ArithmeticException: / by
zero’_.

------------------------------------------------------------------------

try-catch

Apabila _exception_ berlaku, biasanya program akan terus tutup dan code
selepasnya tidak akan dilaksanakan. Contohnya,

package essential; public class BahagiKosong { public static void
main(String[] args) { int a = 1 / 0; System.out.println("ini selepas
bahagi kosong"); } }

+--------------------------------------+--------------------------------------+
| 1                                    | package essential;                   |
|                                      |                                      |
| 2                                    |                                      |
|                                      |                                      |
| 3                                    | public class BahagiKosong {          |
|                                      |                                      |
| 4                                    |     public static void main(String[] |
|                                      | args) {                              |
| 5                                    |                                      |
|                                      |         int a = 1 / 0;               |
| 6                                    |                                      |
|                                      |         System.out.println("ini      |
| 7                                    | selepas bahagi kosong");             |
|                                      |                                      |
| 8                                    |     }                                |
|                                      |                                      |
|                                      | }                                    |
+--------------------------------------+--------------------------------------+

Jika kita mahu _run_ code selepasnya, kita mesti handle _exception_ itu
secara manual. Untuk handle _exception_, kita boleh menggunakan
_try-catch_ seperti berikut:

package essential; public class BahagiKosong { public static void
main(String[] args) { try { int a = 1 / 0; } catch (ArithmeticException
e) { System.out.println("tidak boleh bahagi kosong!"); }
System.out.println("ini selepas bahagi kosong"); } }

+--------------------------------------+--------------------------------------+
| 1                                    | package essential;                   |
|                                      |                                      |
| 2                                    |                                      |
|                                      |                                      |
| 3                                    | public class BahagiKosong {          |
|                                      |                                      |
| 4                                    |     public static void main(String[] |
|                                      | args) {                              |
| 5                                    |                                      |
|                                      |         try {                        |
| 6                                    |                                      |
|                                      |             int a = 1 / 0;           |
| 7                                    |                                      |
|                                      |         } catch (ArithmeticException |
| 8                                    | e) {                                 |
|                                      |                                      |
| 9                                    |             System.out.println("tida |
|                                      | k                                    |
| 10                                   | boleh bahagi kosong!");              |
|                                      |                                      |
| 11                                   |         }                            |
|                                      |                                      |
| 12                                   |                                      |
|                                      |                                      |
| 13                                   |         System.out.println("ini      |
|                                      | selepas bahagi kosong");             |
|                                      |                                      |
|                                      |     }                                |
|                                      |                                      |
|                                      | }                                    |
+--------------------------------------+--------------------------------------+

------------------------------------------------------------------------

finally

Satu tambahan kepada _try-catch_ ialah _finally_. Code di dalam
_finally_ akan wajib dilaksanakan. Ini bertujuan jika ada _exception_
lain yang tidak disangkakan berlaku.

package essential; public class BahagiKosong { public static void
main(String[] args) { try { int a = 1 / 0; } catch (ArithmeticException
e) { System.out.println("tidak boleh bahagi kosong!"); } finally {
System.out.println("ini confirm dilaksanakan"); }
System.out.println("ini selepas bahagi kosong"); } }

+--------------------------------------+--------------------------------------+
| 1                                    | package essential;                   |
|                                      |                                      |
| 2                                    |                                      |
|                                      |                                      |
| 3                                    | public class BahagiKosong {          |
|                                      |                                      |
| 4                                    |     public static void main(String[] |
|                                      | args) {                              |
| 5                                    |                                      |
|                                      |         try {                        |
| 6                                    |                                      |
|                                      |             int a = 1 / 0;           |
| 7                                    |                                      |
|                                      |         } catch (ArithmeticException |
| 8                                    | e) {                                 |
|                                      |                                      |
| 9                                    |             System.out.println("tida |
|                                      | k                                    |
| 10                                   | boleh bahagi kosong!");              |
|                                      |                                      |
| 11                                   |         } finally {                  |
|                                      |                                      |
| 12                                   |             System.out.println("ini  |
|                                      | confirm dilaksanakan");              |
| 13                                   |                                      |
|                                      |         }                            |
| 14                                   |                                      |
|                                      |                                      |
| 15                                   |                                      |
|                                      |         System.out.println("ini      |
|                                      | selepas bahagi kosong");             |
|                                      |                                      |
|                                      |     }                                |
|                                      |                                      |
|                                      | }                                    |
+--------------------------------------+--------------------------------------+

------------------------------------------------------------------------

throws

Kita boleh menggunakan _throws_ bagi menggantikan _catch_. Bezanya kita
tidak boleh handle _exception_ secara manual jika menggunakan _throws_.

package essential; public class BahagiKosong { public static void
main(String[] args) throws ArithmeticException { try { int a = 1 / 0; }
finally { System.out.println("ini confirm berlaku"); }
System.out.println("ini selepas bahagi kosong"); } }

+--------------------------------------+--------------------------------------+
| 1                                    | package essential;                   |
|                                      |                                      |
| 2                                    |                                      |
|                                      |                                      |
| 3                                    | public class BahagiKosong {          |
|                                      |                                      |
| 4                                    |     public static void main(String[] |
|                                      | args) throws ArithmeticException {   |
| 5                                    |                                      |
|                                      |         try {                        |
| 6                                    |                                      |
|                                      |             int a = 1 / 0;           |
| 7                                    |                                      |
|                                      |         } finally {                  |
| 8                                    |                                      |
|                                      |             System.out.println("ini  |
| 9                                    | confirm berlaku");                   |
|                                      |                                      |
| 10                                   |         }                            |
|                                      |                                      |
| 11                                   |                                      |
|                                      |                                      |
| 12                                   |         System.out.println("ini      |
|                                      | selepas bahagi kosong");             |
| 13                                   |                                      |
|                                      |     }                                |
|                                      |                                      |
|                                      | }                                    |
+--------------------------------------+--------------------------------------+

